# Generated by Django 3.1.6 on 2021-06-25 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loaner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default='', null=True)),
                ('EmailAddress', models.TextField(default='')),
                ('ResidenceAddress', models.TextField(default='')),
                ('ZipCode', models.TextField(default='')),
                ('DateOfBirth', models.TextField(default='')),
                ('Status', models.TextField(default='')),
                ('Citizenship', models.TextField(default='')),
                ('CellNo', models.TextField(default='', max_length=12)),
                ('ValidID', models.TextField(default='')),
                ('ValidIDNo', models.CharField(default='', max_length=15)),
                ('Income', models.TextField(default='')),
                ('Employment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.TextField(default='')),
                ('Password', models.TextField(default='', max_length=10)),
                ('LoanId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LoanApp.loaner')),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentMethod', models.TextField(default='')),
                ('AccountNumber', models.TextField(default='')),
                ('LoanId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LoanApp.loaner')),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyBranch', models.TextField(default='')),
                ('BankBranch', models.TextField(default='')),
                ('RemitanceCenter', models.TextField(default='')),
                ('Location', models.TextField(default='')),
                ('LoanId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LoanApp.loaner')),
            ],
        ),
        migrations.CreateModel(
            name='AmountLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AmountLoan', models.CharField(default='', max_length=1000000)),
                ('Interest', models.CharField(default='', max_length=100)),
                ('Months', models.CharField(default='', max_length=72)),
                ('Payment', models.CharField(default='', max_length=1000000)),
                ('LoanId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LoanApp.loaner')),
            ],
        ),
    ]
