# Generated by Django 3.1.6 on 2021-06-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loaner',
            old_name='Name',
            new_name='FullName',
        ),
    ]
