# Generated by Django 3.1.6 on 2021-06-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0002_auto_20210625_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='CompanyBranch',
        ),
    ]
