# Generated by Django 3.1.6 on 2021-06-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0003_remove_branches_companybranch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountloan',
            old_name='AmountLoan',
            new_name='Amount',
        ),
    ]
