# Generated by Django 3.1.6 on 2021-06-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0005_auto_20210625_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountloan',
            old_name='Amount',
            new_name='AmountLoan',
        ),
    ]
