# Generated by Django 3.1.6 on 2021-06-01 14:23

import LoanApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0005_auto_20210601_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyBranch', models.TextField(default='')),
                ('BankBranch', models.TextField(default='')),
                ('LoanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoanApp.loaner')),
            ],
        ),
        migrations.RenameModel(
            old_name='AmountLoan',
            new_name='Amount',
        ),
        migrations.DeleteModel(
            name='LogIn',
        ),
        migrations.RemoveField(
            model_name='item',
            name='BankBranch',
        ),
        migrations.RemoveField(
            model_name='item',
            name='CompanyBranch',
        ),
        migrations.RemoveField(
            model_name='item',
            name='LoanId',
        ),
        migrations.AddField(
            model_name='item',
            name='EmailAddress',
            field=models.TextField(default='', verbose_name=LoanApp.models.Loaner),
        ),
        migrations.AddField(
            model_name='item',
            name='FullName',
            field=models.TextField(default='', verbose_name=LoanApp.models.Loaner),
        ),
        migrations.AddField(
            model_name='item',
            name='Password',
            field=models.TextField(default='', verbose_name=LoanApp.models.Loaner),
        ),
    ]
