# Generated by Django 3.1.6 on 2021-06-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0006_auto_20210601_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='EmailAddress',
        ),
        migrations.RemoveField(
            model_name='item',
            name='FullName',
        ),
        migrations.AddField(
            model_name='item',
            name='UserName',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='Password',
            field=models.TextField(default='', max_length=10),
        ),
    ]
