# Generated by Django 3.1.6 on 2021-06-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0008_auto_20210601_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='LoanId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LoanApp.loaner'),
        ),
    ]
