# Generated by Django 3.1.6 on 2021-06-15 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0010_item_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.TextField(default='')),
                ('Password', models.TextField(default='', max_length=10)),
                ('LoanId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LoanApp.loaner')),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.TextField(default='')),
                ('Password', models.TextField(default='', max_length=10)),
                ('LoanId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LoanApp.loaner')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
