# Generated by Django 3.1.6 on 2021-06-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0011_auto_20210615_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogIn',
        ),
    ]
