# Generated by Django 3.1.6 on 2021-06-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0012_delete_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repayment',
            old_name='GuidelinePayment',
            new_name='AccountNumber',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='PayNow',
        ),
        migrations.AddField(
            model_name='branches',
            name='Location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='branches',
            name='RemitanceCenter',
            field=models.TextField(default=''),
        ),
    ]
