# Generated by Django 3.1.6 on 2021-06-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0013_auto_20210616_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amountloan',
            name='integer',
        ),
    ]
