# Generated by Django 3.1.6 on 2021-06-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0014_remove_amountloan_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountloan',
            name='Payment',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
