from selenium import webdriver 
#import unittest
from selenium.webdriver.common.keys import Keys
import time
from django.test import LiveServerTestCase
from selenium.common.exceptions import WebDriverException

cWait = 3
class PageTesting(LiveServerTestCase):

	def setUp(self):
		self.browser = webdriver.Firefox()

	def tearDown(self):
		self.browser.quit()
	
	def wait_rows_in_listtable(self, row_text):                                   
		start_time = time.time()
		while time.time()-start_time<cWait:
			time.sleep(0.1)
		try:
			table = self.browser.find_element_by_id('Table')
			rows = table.find_elements_by_tag_name('tr')
			self.assertIn(row_text, [row.text for row in rows])
			return
		except(AssertionError, WebDriverException) as e:
			if time.time()-start_time>cWait:
				raise e

		#table = self.browser.find_element_by_id('Table')
		#rows = table.find_elements_by_tag_name('tr')
		#self.assertIn(row_text, [row.text for row in rows])

	def test_start_list_one_user(self):
		self.browser.get(self.live_server_url)
		self.assertIn('Loan Application', self.browser.title)
		hText = self.browser.find_element_by_tag_name('h1').text
		self.assertIn('Loan Application Form', headerText)

		inName = self.browser.find_element_by_id('FullName')
		inName.click()
		inName.send_keys('Ariel B. Sabalboro')
		time.sleep(.1)
		inEmail = self.browser.find_element_by_id('EmailAddress')
		inEmail.click()
		inEmail.send_keys('ArielSabalboro@gmail.com')
		time.sleep(.1)
		inAddress = self.browser.find_element_by_id('ResidenceAddress')
		inAddress.click()
		inAddress.send_keys('Maligaya street, San Simon, Dasmarinas City')
		time.sleep(.1)
		inCode = self.browser.find_element_by_id('ZipCode')
		inCode.click()
		inCode.send_keys('4114')
		time.sleep(.1)
		inDate = self.browser.find_element_by_id('DateOfBirth')
		inDate.click()
		inDate.send_keys('03/04/2000')
		time.sleep(.1)
		inStatus = self.browser.find_element_by_id('MaritalStatus')
		inStatus.click()
		inStatus.send_keys('Single')
		time.sleep(.1)
		inCitizenship = self.browser.find_element_by_id('Citizenship')
		inCitizenship.click()
		inCitizenship.send_keys('Filipino')
		time.sleep(.1)
		inCPNo = self.browser.find_element_by_id('CellphoneNo')
		inCPNo.click()
		inCPNo.send_keys('09876543210')
		time.sleep(.1)
		selectValidID = self.browser.find_element_by_id('ValidID')
		selectValidID.click()
		selectValidID.send_keys(Keys.ARROW_DOWN)
		time.sleep(.1)
		inValidIDNo = self.browser.find_element_by_id('ValidIDNo')
		inValidIDNo.click()
		inValidIDNo.send_keys('123-4567-890')
		time.sleep(.1)
		selectIncome = self.browser.find_element_by_id('Income')
		selectIncome.click()
		selectIncome.send_keys(Keys.ARROW_DOWN)
		time.sleep(.1)
		selectEmployment = self.browser.find_element_by_id('Employment')
		selectEmployment.click()
		selectEmployment.send_keys(Keys.ARROW_DOWN)
		time.sleep(.1)
		inConfirm = self.browser.find_element_by_id('inConfirm')
		inConfirm.click()
		self.wait_rows_in_listtable('1: Ariel B. Sabalboro')

		time.sleep(.1)
		inName = self.browser.find_element_by_id('FullName')
		inName.click()
		inName.send_keys('Fhae D. Encenares')
		time.sleep(.1)
		inEmail = self.browser.find_element_by_id('EmailAddress')
		inEmail.click()
		inEmail.send_keys('Enenares_Fhaechi@gmail.com')
		time.sleep(.1)
		inAddress = self.browser.find_element_by_id('ResidenceAddress')
		inAddress.click()
		inAddress.send_keys('Blk O, San Andres 1, Dasmarinas City')
		time.sleep(.1)
		inCode = self.browser.find_element_by_id('ZipCode')
		inCode.click()
		inCode.send_keys('4114')
		time.sleep(.1)
		inDate = self.browser.find_element_by_id('DateOfBirth')
		inDate.click()
		inDate.send_keys('04/12/2000')
		time.sleep(.1)
		inStatus = self.browser.find_element_by_id('MaritalStatus')
		inStatus.click()
		inStatus.send_keys('Single')
		time.sleep(.1)
		inCitizenship = self.browser.find_element_by_id('Citizenship')
		inCitizenship.click()
		inCitizenship.send_keys('Filipino')
		time.sleep(.1)
		inCPNo = self.browser.find_element_by_id('CellphoneNo')
		inCPNo.click()
		inCPNo.send_keys('0908976543215')
		time.sleep(.1)
		selectValidID = self.browser.find_element_by_id('ValidID')
		selectValidID.click()
		selectValidID.send_keys(Keys.ARROW_DOWN)
		time.sleep(.1)
		inValidIDNo = self.browser.find_element_by_id('ValidIDNo')
		inValidIDNo.click()
		inValidIDNo.send_keys('043-9875-126')
		time.sleep(.1)
		selectIncome = self.browser.find_element_by_id('Income')
		selectIncome.click()
		selectIncome.send_keys(Keys.ARROW_DOWN)
		time.sleep(.1)
		selectEmployment = self.browser.find_element_by_id('Employment')
		selectEmployment.click()
		selectEmployment.send_keys(Keys.ARROW_DOWN)
		time.sleep(.1)
		inConfirm = self.browser.find_element_by_id('inConfirm')
		inConfirm.click()
		self.wait_rows_in_listtable('2: Fhae D. Encenares')

	def test_other_users_different_urls(self):
		self.browser.get(self.live_server_url)
		time.sleep(.1)
		inName = self.browser.find_element_by_id('FullName')
		inName.click()
		inName.send_keys('Jhonas C. Asna')
		time.sleep(.1)
		inEmail = self.browser.find_element_by_id('EmailAddress')
		inEmail.click()
		inEmail.send_keys('JhongAsna@gmail.com')
		time.sleep(.1)
		inAddress = self.browser.find_element_by_id('ResidenceAddress')
		inAddress.click()
		inAddress.send_keys('Blk K, Sta. Cristina 1, Dasmarinas City')
		time.sleep(.1)
		inCode = self.browser.find_element_by_id('ZipCode')
		inCode.click()
		inCode.send_keys('4114')
		time.sleep(.1)
		inDate = self.browser.find_element_by_id('DateOfBirth')
		inDate.click()
		inDate.send_keys('02/03/1995')
		time.sleep(.1)
		inStatus = self.browser.find_element_by_id('MaritalStatus')
		inStatus.click()
		inStatus.send_keys('Single')
		time.sleep(.1)
		inCitizenship = self.browser.find_element_by_id('Citizenship')
		inCitizenship.click()
		inCitizenship.send_keys('Filipino')
		time.sleep(.1)
		inCPNo = self.browser.find_element_by_id('CellphoneNo')
		inCPNo.click()
		inCPNo.send_keys('090754368219')
		time.sleep(.1)
		selectValidID = self.browser.find_element_by_id('ValidID')
		selectValidID.click()
		selectValidID.send_keys(Keys.ARROW_DOWN)
		time.sleep(.1)
		inValidIDNo = self.browser.find_element_by_id('ValidIDNo')
		inValidIDNo.click()
		inValidIDNo.send_keys('067-9543-281')
		time.sleep(.1)
		selectIncome = self.browser.find_element_by_id('Income')
		selectIncome.click()
		selectIncome.send_keys(Keys.ARROW_DOWN)
		time.sleep(.1)
		selectEmployment = self.browser.find_element_by_id('Employment')
		selectEmployment.click()
		selectEmployment.send_keys(Keys.ARROW_DOWN)
		time.sleep(.1)
		inConfirm = self.browser.find_element_by_id('inConfirm')
		inConfirm.click()
		self.wait_rows_in_listtable('1: Jhonas C. Asna')
		viewlist_url = self.browser.current_url
		self.assertRegex(viewlist_url, '/LoanApp/.+')

		self.browser.quit()
		self.browser = webdriver.Firefox()
		self.browser.get(self.live_server_url)
		pageBody = self.browser.find_element_by_tag_name('body').text
		self.assertNotIn('Jhonas C. Asna', pageBody)
		time.sleep(.1)
		inName = self.browser.find_element_by_id('FullName')
		inName.click()
		inName.send_keys('Rhonalyn M. Gonzales')
		time.sleep(.1)
		inEmail = self.browser.find_element_by_id('EmailAddress')
		inEmail.click()
		inEmail.send_keys('RhonalengMG_45@gmail.com')
		time.sleep(.1)
		inAddress = self.browser.find_element_by_id('ResidenceAddress')
		inAddress.click()
		inAddress.send_keys('123 Kundiman Street, Sampaloc Manila')
		time.sleep(.1)
		inCode = self.browser.find_element_by_id('ZipCode')
		inCode.click()
		inCode.send_keys('1009')
		time.sleep(.1)
		inDate = self.browser.find_element_by_id('DateOfBirth')
		inDate.click()
		inDate.send_keys('10/11/1987')
		time.sleep(.1)
		inStatus = self.browser.find_element_by_id('MaritalStatus')
		inStatus.click()
		inStatus.send_keys('Married')
		time.sleep(.1)
		inCitizenship = self.browser.find_element_by_id('Citizenship')
		inCitizenship.click()
		inCitizenship.send_keys('Filipino')
		time.sleep(.1)
		inCPNo = self.browser.find_element_by_id('CellphoneNo')
		inCPNo.click()
		inCPNo.send_keys('095086793124')
		time.sleep(.1)
		selectValidID = self.browser.find_element_by_id('ValidID')
		selectValidID.click()
		selectValidID.send_keys(Keys.ARROW_DOWN)
		time.sleep(.1)
		inValidIDNo = self.browser.find_element_by_id('ValidIDNo')
		inValidIDNo.click()
		inValidIDNo.send_keys('034-5927-816')
		time.sleep(.1)
		selectIncome = self.browser.find_element_by_id('Income')
		selectIncome.click()
		selectIncome.send_keys(Keys.ARROW_DOWN)
		time.sleep(.1)
		selectEmployment = self.browser.find_element_by_id('Employment')
		selectEmployment.click()
		selectEmployment.send_keys(Keys.ARROW_DOWN)
		time.sleep(.1)
		inConfirm = self.browser.find_element_by_id('inConfirm')
		inConfirm.click()
		self.wait_rows_in_listtable('1: Rhonalyn M. Gonzales')
		user2_url = self.browser.current_url
		self.assertRegex(user2_url, 'LoanApp/.+')
		self.assertNotEqual(viewlist_url, user2_url)
		pageBody = self.browser.find_element_by_tag_name('body').text
		self.assertNotIn('Jhonas C. Asna', pageBody)
		self.assertIn('Rhonalyn M. Gonzales', pageBody)


	#self.fail('Finish the test!')

#def test_browser_title(self):
	#	self.browser.get('http://localhost:8000')
	#	self.assertIn('Loan Application', self.browser.title)
	#	self.fail('Finish the test!')

	#btnMore.click()
	#time.sleep(2)
	#btnMore = self.browser.find_element_by_id('btnMore')

	#table = self.browser.find_element_by_id('idListTable')
	#rows = table.find_elements_by_tag_name('tr')
	#self.assertIn('1:Juana S. Dela Cruz in Juanadelacruz@gmail.com', [row.text for row in rows])
	#self.assertIn('2:Prince J. Valdez in Valdez_PrinceJ@gmail.com', [row.text for row in rows])
	#self.assertTrue(any(row.text =='1: Juana A. Cruz'))
	#self.assertEqual(inputEmail.get_attribute('placeholder'),'Your Email Address')
	#self.assertEqual(inputValidID.get_attribute('placeholder'),'Types of Valid ID')


#if __name__ == '__main__':
#   unittest.main(warnings='ignore')
