from selenium import webdriver 
#import unittest
from selenium.webdriver.common.keys import Keys
import time
from django.test import LiveServerTestCase
from selenium.common.exceptions import WebDriverException

cWait = 3
class PageTest(LiveServerTestCase):

	def setUp(self):
		self.browser = webdriver.Firefox()

	def tearDown(self):
		self.browser.quit()
	
	def wait_rows_in_loantable(self, row_text):                                   
		start_time = time.time()
		while time.time()-start_time<cWait:
			time.sleep(1)
		try:
			table = self.browser.find_element_by_id('loanTable')
			rows = table.find_elements_by_tag_name('tr')
			self.assertIn(row_text, [row.text for row in rows])
			return
		except(AssertionError, WebDriverException) as e:
			if time.time()-start_time>cWait:
				raise e

		#table = self.browser.find_element_by_id('LoanTable')
		#rows = table.find_elements_by_tag_name('tr')
		#self.assertIn(row_text, [row.text for row in rows])

	def test_start_list_one_user(self):
		self.browser.get(self.live_server_url)
		self.assertIn('Loan Application', self.browser.title)
		headerText = self.browser.find_element_by_tag_name('h1').text
		self.assertIn('Loan Application', headerText)

		inName = self.browser.find_element_by_id('FullName')
		inName.click()
		inName.send_keys('Ariel B. Sabalboro')
		time.sleep(1)
		inEmail = self.browser.find_element_by_id('EmailAddress')
		inEmail.click()
		inEmail.send_keys('ArielSabalboro@gmail.com')
		time.sleep(1)
		inAddress = self.browser.find_element_by_id('ResidenceAddress')
		inAddress.click()
		inAddress.send_keys('San Simon, Dasmarinas City')
		time.sleep(1)
		inCode = self.browser.find_element_by_id('ZipCode')
		inCode.click()
		inCode.send_keys('4114')
		time.sleep(1)
		inDate = self.browser.find_element_by_id('DateOfBirth')
		inDate.click()
		inDate.send_keys('03/04/2000')
		time.sleep(1)
		inStatus = self.browser.find_element_by_id('Status')
		inStatus.click()
		inStatus.send_keys('Single')
		time.sleep(1)
		inCitizenship = self.browser.find_element_by_id('Citizenship')
		inCitizenship.click()
		inCitizenship.send_keys('Filipino')
		time.sleep(1)
		inCPNo = self.browser.find_element_by_id('CellNo')
		inCPNo.click()
		inCPNo.send_keys('09876543210')
		time.sleep(1)
		inValidID = self.browser.find_element_by_id('ValidID')
		inValidID.click()
		inValidID.send_keys('Pag-Ibig ID')
		time.sleep(1)
		inValidIDNo = self.browser.find_element_by_id('ValidIDNo')
		inValidIDNo.click()
		inValidIDNo.send_keys('123-4567-890')
		time.sleep(1)
		inIncome = self.browser.find_element_by_id('Income')
		inIncome.click()
		inIncome.send_keys('Allowance')
		time.sleep(1)
		inEmployment = self.browser.find_element_by_id('Employment')
		inEmployment.click()
		inEmployment.send_keys('Student')
		time.sleep(1)
		btnConfirm = self.browser.find_element_by_id('btnConfirm')
		btnConfirm.click()
		self.wait_rows_in_loantable('1: Ariel B. Sabalboro')

		time.sleep(.1)
		inName = self.browser.find_element_by_id('FullName')
		inName.click()
		inName.send_keys('Fhae D. Encenares')
		time.sleep(1)
		inEmail = self.browser.find_element_by_id('EmailAddress')
		inEmail.click()
		inEmail.send_keys('Enenares_Fhaechi@gmail.com')
		time.sleep(1)
		inAddress = self.browser.find_element_by_id('ResidenceAddress')
		inAddress.click()
		inAddress.send_keys('San Andres 1, Dasmarinas City')
		time.sleep(1)
		inCode = self.browser.find_element_by_id('ZipCode')
		inCode.click()
		inCode.send_keys('4114')
		time.sleep(1)
		inDate = self.browser.find_element_by_id('DateOfBirth')
		inDate.click()
		inDate.send_keys('04/12/2000')
		time.sleep(1)
		inStatus = self.browser.find_element_by_id('Status')
		inStatus.click()
		inStatus.send_keys('Single')
		time.sleep(1)
		inCitizenship = self.browser.find_element_by_id('Citizenship')
		inCitizenship.click()
		inCitizenship.send_keys('Filipino')
		time.sleep(1)
		inCPNo = self.browser.find_element_by_id('CellNo')
		inCPNo.click()
		inCPNo.send_keys('0908976543215')
		time.sleep(1)
		inValidID = self.browser.find_element_by_id('ValidID')
		inValidID.click()
		inValidID.send_keys('Philhealth ID')
		time.sleep(1)
		inValidIDNo = self.browser.find_element_by_id('ValidIDNo')
		inValidIDNo.click()
		inValidIDNo.send_keys('043-9875-126')
		time.sleep(1)
		inIncome = self.browser.find_element_by_id('Income')
		inIncome.click()
		inIncome.send_keys('Salary')
		time.sleep(1)
		inEmployment = self.browser.find_element_by_id('Employment')
		inEmployment.click()
		inEmployment.send_keys('Part-time Employee')
		time.sleep(1)
		btnConfirm = self.browser.find_element_by_id('btnConfirm')
		btnConfirm.click()
		self.wait_rows_in_loantable('2: Fhae D. Encenares')

	def test_other_users_different_urls(self):
		self.browser.get(self.live_server_url)
		time.sleep(.1)
		inName = self.browser.find_element_by_id('FullName')
		inName.click()
		inName.send_keys('Sharalyn B. Dela Cerna')
		time.sleep(1)
		inEmail = self.browser.find_element_by_id('EmailAddress')
		inEmail.click()
		inEmail.send_keys('SharalynDelaCerna@gmail.com')
		time.sleep(1)
		inAddress = self.browser.find_element_by_id('ResidenceAddress')
		inAddress.click()
		inAddress.send_keys('Victoria, Dasmarinas City')
		time.sleep(1)
		inCode = self.browser.find_element_by_id('ZipCode')
		inCode.click()
		inCode.send_keys('4114')
		time.sleep(1)
		inDate = self.browser.find_element_by_id('DateOfBirth')
		inDate.click()
		inDate.send_keys('03/21/1995')
		time.sleep(1)
		inStatus = self.browser.find_element_by_id('Status')
		inStatus.click()
		inStatus.send_keys('Single')
		time.sleep(1)
		inCitizenship = self.browser.find_element_by_id('Citizenship')
		inCitizenship.click()
		inCitizenship.send_keys('Filipino')
		time.sleep(1)
		inCPNo = self.browser.find_element_by_id('CellNo')
		inCPNo.click()
		inCPNo.send_keys('090754368219')
		time.sleep(1)
		inValidID = self.browser.find_element_by_id('ValidID')
		inValidID.click()
		inValidID.send_keys('Voters ID')
		time.sleep(1)
		inValidIDNo = self.browser.find_element_by_id('ValidIDNo')
		inValidIDNo.click()
		inValidIDNo.send_keys('067-9543-281')
		time.sleep(1)
		inIncome = self.browser.find_element_by_id('Income')
		inIncome.click()
		inIncome.send_keys('Salary')
		time.sleep(1)
		inEmployment = self.browser.find_element_by_id('Employment')
		inEmployment.click()
		inEmployment.send_keys('Full-time Employee')
		time.sleep(1)
		btnConfirm = self.browser.find_element_by_id('btnConfirm')
		btnConfirm.click()
		self.wait_rows_in_loantable('1: Sharalyn B. Dela Cerna')
		viewlist_url = self.browser.current_url
		self.assertRegex(viewlist_url, '/LoanApp/.+')

		self.browser.quit()
		self.browser = webdriver.Firefox()
		self.browser.get(self.live_server_url)
		pageBody = self.browser.find_element_by_tag_name('body').text
		self.assertNotIn('Sharalyn B. Dela Cerna', pageBody)
		time.sleep(.1)
		inName = self.browser.find_element_by_id('FullName')
		inName.click()
		inName.send_keys('Jennifer M. Miasco')
		time.sleep(1)
		inEmail = self.browser.find_element_by_id('EmailAddress')
		inEmail.click()
		inEmail.send_keys('JenniferMiasco28@gmail.com')
		time.sleep(1)
		inAddress = self.browser.find_element_by_id('ResidenceAddress')
		inAddress.click()
		inAddress.send_keys('123 Kundiman Street, Sampaloc Manila')
		time.sleep(1)
		inCode = self.browser.find_element_by_id('ZipCode')
		inCode.click()
		inCode.send_keys('1009')
		time.sleep(1)
		inDate = self.browser.find_element_by_id('DateOfBirth')
		inDate.click()
		inDate.send_keys('07/04/1987')
		time.sleep(1)
		inStatus = self.browser.find_element_by_id('Status')
		inStatus.click()
		inStatus.send_keys('Married')
		time.sleep(1)
		inCitizenship = self.browser.find_element_by_id('Citizenship')
		inCitizenship.click()
		inCitizenship.send_keys('Filipino')
		time.sleep(1)
		inCPNo = self.browser.find_element_by_id('CellNo')
		inCPNo.click()
		inCPNo.send_keys('095086793124')
		time.sleep(1)
		inValidID = self.browser.find_element_by_id('ValidID')
		inValidID.click()
		inValidID.send_keys('SSS ID')
		time.sleep(1)
		inValidIDNo = self.browser.find_element_by_id('ValidIDNo')
		inValidIDNo.click()
		inValidIDNo.send_keys('034-5927-816')
		time.sleep(1)
		inIncome = self.browser.find_element_by_id('Income')
		inIncome.click()
		inIncome.send_keys('Pension')
		time.sleep(1)
		inEmployment = self.browser.find_element_by_id('Employment')
		inEmployment.click()
		inEmployment.send_keys('Unemployed')
		time.sleep(1)
		btnConfirm = self.browser.find_element_by_id('btnConfirm')
		btnConfirm.click()
		self.wait_rows_in_loantable('1: Jennifer M. Miasco')
		user2_url = self.browser.current_url
		self.assertRegex(user2_url, 'LoanApp/.+')
		self.assertNotEqual(viewlist_url, user2_url)
		pageBody = self.browser.find_element_by_tag_name('body').text
		self.assertNotIn('Sharalyn Dela Cerna', pageBody)
		self.assertIn('Jennifer M. Miasco', pageBody)





